### ISSUE TITLE
Closing statement Error

### ISSUE THREAD

**Issue by MarceCandil** [davidodenwald/prettier-plugin-jinja-template#18]
Hey guys, I installed it to test it and It returns an error even if the tag is closed correctly. Any idea what's going on?

<img width="1006" alt="Screenshot 2023-08-23 at 10 46 36" src="https://github.com/davidodenwald/prettier-plugin-jinja-template/assets/11147260/d753ff72-56e4-4531-bf6d-404ef9273ee7">

**Comment by davidodenwald** [comment]
I guess you are talking about these [custom Jinja tags](https://developers.hubspot.com/docs/cms/hubl/tags/dnd-areas).

The current logic of this plugin is to match closing statements by prepending "end" to the opening statement.
So the closing statement should be "enddnd_area".

If there is still interest, I can extend the logic so that end statements starting with "end_" are also recognized.

**Comment by jlarmstrongiv** [comment]
Supporting both `enddnd_area` and `end_dnd_area` (end statements starting with `end_`) would be wonderful 😄

**Comment by davidodenwald** [comment]
This should work with the latest release.
