### ISSUE TITLE
Syntax Error with templates inside script tags.

### ISSUE THREAD

**Issue by MilyMilo** [davidodenwald/prettier-plugin-jinja-template#21]
Hi! First of all thank you for this project! 

Prettier formatting for jinja itself seems neat, but now I'm able to use prettier plugins such as the tailwind plugin which is what does make a huge difference for me!

When working my project I've got a syntax error with code like this:
```
{% block scripts %}
<script>
	var STATE = {{ state | tojson }};
</script>
{% endblock %}
```

```
[error] templates/setup.html: SyntaxError: Unexpected token (2:15)
[error]   1 |
[error] > 2 |   var STATE = {{ state | tojson }};
[error]     |                ^
[error]   3 |
```

This does not happen when I'm running prettier without the jinja plugin. I'm unsure how is the plugin treating script blocks, but the issue seems to be specific to them, I'm also unable to ignore this code with prettier-ignore in both html and js.

**Comment by davidodenwald** [comment]
This plugin relies on errors by "embedded" languages to bubble up in contrast to the default html plugin which ignores these errors.

The easiest way to ignore these kinds of errors is by adding a [range ignore](https://prettier.io/docs/en/ignore#range-ignore) around the script block:

```html
<!-- prettier-ignore-start -->
  {% block scripts %}
    <script>
      var STATE = {{ state | tojson }};
    </script>
  {% endblock %}
<!-- prettier-ignore-end -->

```

**Comment by PetrDlouhy** [comment]
Hm, this is pitty, because it makes `prettier-plugin-jinja-template` practically unusable, at least for me.
This means that:
- I would have to add those comments around every script block manually.
- Those script block wouldn't be formatted by prettier.
- When I add new `script` block and forget those comments, it would break the code in it if I run the re-formatter automatically.
